version: 2.1

orbs:
  moul: moul/build@1.12.1 # https://github.com/moul/build

workflows:
  main:
    jobs:
      - moul/golang-build:
          prepare-build: sudo apt install libportmidi-dev
          gopkg: moul.io/music-paint
      - moul/golang-build:
          prepare-build: sudo apt install libportmidi-dev
          gopkg: moul.io/music-paint
          tag: '1.16'
      - moul/golang-build:
          prepare-build: sudo apt install libportmidi-dev
          gopkg: moul.io/music-paint
          tag: '1.15'
      - moul/docker-build
